# dbt Project Configuration for Fabric Data Platform

name: 'fabric_data_platform'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'fabric_data_platform'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  fabric_data_platform:
    # Bronze models - raw data ingestion and light transformations
    bronze:
      +materialized: view
      +schema: bronze
      +tags:
        - "bronze"
        - "raw"
      
    # Silver models - cleansed and conformed data
    silver:
      +materialized: view
      +schema: silver
      +tags:
        - "silver"
        - "transformed"
      
    # Gold models - business-ready, aggregated, certified data
    gold:
      +materialized: table
      +schema: gold
      +tags:
        - "gold"
        - "certified"
      # These are the models BUs will consume
      +meta:
        owner: "data-engineering"
        certified: true

# Seeds configuration
seeds:
  fabric_data_platform:
    +schema: seeds

# Tests
tests:
  fabric_data_platform:
    +store_failures: true
    +schema: test_results

# Documentation
docs-paths: ["docs"]

# Snapshots
snapshots:
  fabric_data_platform:
    +target_schema: snapshots
    +unique_key: id
    +strategy: timestamp
    +updated_at: updated_at
