# dbt Profiles Configuration for Fabric Data Platform

fabric_data_platform:
  target: dev
  outputs:
    dev:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server'
      server: your-fabric-workspace.datawarehouse.fabric.microsoft.com
      port: 1433
      database: your_lakehouse
      schema: dbo
      authentication: CLI
      # Use Azure CLI authentication by default
      
    prod:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server'
      server: your-fabric-workspace-prod.datawarehouse.fabric.microsoft.com
      port: 1433
      database: your_lakehouse_prod
      schema: dbo
      authentication: CLI
      
# Alternative authentication methods:
# 
# Service Principal:
#   authentication: serviceprincipal
#   tenant_id: "{{ env_var('AZURE_TENANT_ID') }}"
#   client_id: "{{ env_var('AZURE_CLIENT_ID') }}"
#   client_secret: "{{ env_var('AZURE_CLIENT_SECRET') }}"
#
# Managed Identity:
#   authentication: msi
