# dbt Profiles Configuration for Fabric Data Platform

fabric_data_platform:
  target: dev
  outputs:
    dev:
      type: fabric
      driver: 'ODBC Driver 17 for SQL Server'
      server: yxe6ecc263mezdjvuarhfykc2y-ksnb7qqzd4iufenweci5kyijy4.datawarehouse.fabric.microsoft.com
      port: 1433
      database: core_warehouse_dev
      schema: dbo
      authentication: CLI
      # Use Azure CLI authentication by default
      
    test:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server'
      server: yxe6ecc263mezdjvuarhfykc2y-7kr47n2iypguze3ls5ez5zfzf4.datawarehouse.fabric.microsoft.com
      port: 1433
      database: core_warehouse_test
      schema: dbo
      authentication: CLI
      
    prod:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server'
      server: yxe6ecc263mezdjvuarhfykc2y-r3dt27ase72ezpzrfbv35ebihq.datawarehouse.fabric.microsoft.com
      port: 1433
      database: core_warehouse_prod
      schema: dbo
      authentication: CLI
      
# Alternative authentication methods:
# 
# Service Principal:
#   authentication: serviceprincipal
#   tenant_id: "{{ env_var('AZURE_TENANT_ID') }}"
#   client_id: "{{ env_var('AZURE_CLIENT_ID') }}"
#   client_secret: "{{ env_var('AZURE_CLIENT_SECRET') }}"
#
# Managed Identity:
#   authentication: msi
