version: 2

models:
  - name: brz_demo__customers
    description: Bronze layer for demo customer data - raw ingestion with basic cleaning and type casting
    columns:
      - name: customer_id
        description: Unique identifier for each customer
        tests:
          - unique
          - not_null
      
      - name: customer_name
        description: Full name of the customer (trimmed)
        tests:
          - not_null
      
      - name: email
        description: Customer email address (lowercase, trimmed)
        tests:
          - not_null
          - unique
      
      - name: signup_date
        description: Date when the customer signed up
        tests:
          - not_null
      
      - name: status
        description: Current customer status (normalized to lowercase)
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'inactive', 'churned']
      
      - name: country
        description: Country where the customer is located
        tests:
          - not_null
      
      - name: lifetime_value
        description: Total revenue generated from this customer
        tests:
          - not_null
      
      - name: _loaded_at
        description: Timestamp when the record was loaded into bronze layer
